export const workoutOptions = {
	'Aerobics':[
		'Boxing',
		'Burpees',
		'Dancing',
		'Eliptical',
		'Jump Rope',
		'Jumping Jacks',
		'Running',
		'Swimming',
		'Stair Climber',
		'Step Machine',
	],
	'Weight':[
		'Bicep Curls',
		'Seated Tricep Extensions',
		'Back Extensions',
		'Bench Press',
		'Deadlifts',
		'Lat Pull-downs',
		'Lateral Raises',
		'Leg Curls',
		'Leg Extensions',
		'Leg Presses',
  ],
	'Calisthenics':[
		'Crunches',
		'Leg Raises',
		'Lunges',
		'Mountain Climbers',
		'Plank',
		'Push-ups',
		'Sit-ups',
		'Squats',
		'Stretching',
		'Yoga',
  ]
}